### ISSUE TITLE
Document how to make routes with no animations

### ISSUE THREAD

**Issue by tomgilder** [tomgilder/routemaster#100]
Including back animations, which isn't obvious

**Comment by RastislavMirek** [comment]
Very much needed especially I could not find any way how to do it. Tried with `transitionDelegate` but `transitionDelegate`  supplied in `Routermaster`'s constructor does not seem to be called at all.

**Comment by tomgilder** [comment]
Done: https://github.com/tomgilder/routemaster/wiki/FAQs#how-do-i-disable-all-page-animations
