### ISSUE TITLE
Pages get rebuilt when not needed with PageStackNavigator in v0.8.0

### ISSUE THREAD

**Issue by rydmike** [tomgilder/routemaster#101]
Pages get rebuilt in v0.8.0 with PageStackNavigator. This does not happen with v0.7.2 and StackNavigator. E.g. when using StatefulWidget for a page, initState is called again and everything is rebuilt from scratch, even when it should not be.

I do not get this rebuild if I downgrade to v 0.7.2 with the same project, but with v0.8.0 I get them. The only change between the builds is changing from StackNavigator to PageStackNavigator. 

If I use the deprecated name/version StackNavigator with v0.8.0 the extra rebuild still happens. A downgrade to version 0.7.2 is required to avoid it and to get things working as before.

Sorry I have not looked into the issue enough yet to have minimum repeatable case. I might post an example later.

**Comment by tomgilder** [comment]
Hmm, tried to reproduce here but no luck so fa r- might be useful to come up with a test case though: https://github.com/tomgilder/routemaster/blob/rebuild/test/page_rebuild_test.dart

**Comment by rydmike** [comment]
I will see what I can come up with to repro it, out of my complicated experimental setup.
It happens in the setup described in: https://github.com/tomgilder/routemaster/issues/88

With version 0.8.0 everything gets rebuilt when I toggle the application's themeMode or modify the themes, it behaves like the entire route stack gets rebuilt, when you do that, so all screens rebuild and they loose state.

This issue makes the latest routemaster version unviable. With 0.7.2 it works OK, apart from the issues/questions/scenarios already described in https://github.com/tomgilder/routemaster/issues/88, that I btw still have not been able to figure out if and how they can be solved.

I could probably create small equivalent replica of the setup in https://github.com/tomgilder/routemaster/issues/88 using a mock design based on NavigationRail and BottomNavigationBar to both demonstrate this issue and the challenges described in https://github.com/tomgilder/routemaster/issues/88 as well.

For this issue I might be able to make a test to demo it too though.

I think the issue might not be rebuilds in general, perhaps it only concerns that all pages get rebuilt completely when you change the properties on MaterialApp.router, like theme, darkTheme and themeMode. Normally when you do that, the page you are doing the change from will keep its scroll position and state, initState, will not be called again, if it is a stateful widget. Now in v 0.8.0 it does, but not with 0.7.2. It also resets the state of all none visible pages that are in my "keep in memory" nav, so they loose their scroll position too and are built again when you navigate to them, with 0.7.2 it does not do that either.

Just noticed this issue late last night, and have not looked very much into it yet. I will dig more, but perhaps the above provides some additional clues to the cause.

**Comment by tomgilder** [comment]
Ah, I think I know what's causing this (but I'm currently out having brunch so I can't check just yet [you probably didn't need to know that (review: Southpark, it's okay, but bit overpriced and no juice included)])

**Comment by rydmike** [comment]
Cool and no worries or hurry. My issue drop yesterday was done quickly, just in order to capture the issue. It was not so descriptive. If you already got an idea of what might cause it from the above addition, that's great.

Regardless of that, I might whip up the example that I mentioned above anyway, just to demo the routemaster use cases I'm pondering about. 

However, it might be a while, as I just got my darn mouse usage caused repetitive stress syndrome back yesterday. Keeping pressure on the inflamed tendon/muscle with a thick tennis elbow band to relive tension in it, plus thick layers of Voltaren, to try to heal it before it gets worse, usually this helps, but I should also try to avoid mouseing around a lot for the next few days 😞 There some info you did not need to know either, hehe 😄

**Comment by tomgilder** [comment]
Yeah, I've reproduced this now: https://github.com/tomgilder/routemaster/blob/rebuild/test/page_rebuild_test.dart

It happens when the `RoutemasterDelegate` object gets recreated. If you store `RoutemasterDelegate` as, for example, a property within `State` it shouldn't happen.

Need to think through the design of this, it's a little difficult; I need to detect when the route map has changed and do a complete rebuild, but not in this case.

Hope your RSI gets better :-(

**Comment by rydmike** [comment]
I was just playing with it a bit more, and noticed the same.

I also noticed that in v. 0.7.2 the `routesBuilder` was not getting called correctly, so I assume that is what this fix was for: https://github.com/tomgilder/routemaster/commit/8967210b73262bcb8764e882ed1cc43085e77354

Which then I guess led to current situation where it is being called even when it has not changed, like when other props in `MaterialApp.router` are changed, effectively causing all pages to rebuild, which is what I experienced.

I browsed what is going on a bit, without going into depths of it, and yeah I figured it might be a bit tricky. Would be a pity if we have to store the `RouteMasterdelegate` within `State`, a bit unintuitive to how things normally work, but I think it should work as temp fix at least, I will try it.

**Comment by tomgilder** [comment]
Yes - it's all because of the ability to swap out route maps at runtime. 

If the `RouteMap` has changed then the current route needs to be rebuilt, because the page _might_ have changed. For instance the root path `/` could be mapped to `LoginPage`, then the user logs in, and it's changed to `HomePage`.

This was happening fine when something in the `routesBuilder` forced a rebuild of that method, but not if the entire `RoutemasterDelegate` was swapped. But now when the delegate is changed, it's doing a full rebuild in case the route map has changed, and recreating pages unnecessarily.

There are _so_ many potential design solutions here!...

1. **Go back to the previous behaviour and add a `key` to force a rebuild**
If `delegateOld.key != delegateNew.key` then rebuild, like Flutter widgets.

2. **Go back to the previous behaviour and add a `rebuild` method**
Similar to above, but more explicit. Probably my least favourite option.

3. **Try to intelligently guess if the route map has changed**
For example, looking at the number of routes in the map - or do a deeper equality compare.

4. **Compare return values**
After a rebuild, inspect the `Page` returned to see if it's different. Otherwise don't rebuild app.

5. **Some mixture of the above**

And probably more I haven't thought of yet...

**Comment by rydmike** [comment]
Sounds complicated and I thought it might indeed be so! 😃 

I played a bit more with my rewrite/fork of the 'mobile_app' example.
You can find it here: https://github.com/rydmike/mrnavdemo

It is now using routemaster 0.8.0, plus I wanted to try it with Riverpod instead of Provider, so that mod is done as well.
And I added some theming that can be toggled via the Settings page.

And when you do that pages are rebuilt, which they should not be, the theme toggling is no also choppy, not smooth as it should be and normally is, with theme change animation.

Also even if I tried a version with the `RoutemasterDelegate` in State I could not really get it to stop rebuilding things when toggling theme.

If I make version of this experiment with 0.7.2, I can do one that behaves better and does not rebuild pages, but yeah, then rebuilds you mention and need above does not work with that version at all.

Here is a demo, and hsowing how it resets state on Settings when theme is toggled:
(towards the end of the animation, wanted to show first that otherwise it keeps state when navigating just fine).

![routemast1](https://user-images.githubusercontent.com/39990307/118405915-aa0e4e00-b682-11eb-925b-a74568b57f55.gif)

**Comment by tomgilder** [comment]
Just published 0.8.1 - it reverts the change that caused this whilst I figure out a better solution. Can you confirm it fixes it @rydmike?

**Comment by tomgilder** [comment]
Turns out there's option 6 - don't do any of those other options and just fix the damn thing 😁

**Comment by rydmike** [comment]
Interesting, commit, quite significant changes, looking forward to trying it out. 

And to answer your question, with the reverted version 0.8.1, nope did not fully work either, parts were better others worse. I could not figure out how to get it to rebuild when it then actually should do so, not when using Riverpod at least, I tried a lot of variants, but no. So if you were not changing the delegate it worked fine, but since the example included many dynamic changes to it, it did not work correctly.

**Comment by tomgilder** [comment]
@rydmike aiming to get this fully sorted for 0.9.0 - just published prerelease 0.9.0-dev1, can you see if that fixes your issues please?

**Comment by rydmike** [comment]
@tomgilder I can confirm that your magical fixes in 0.9.0-dev1 appears to be working. 👍🏻 😃 

This is shown in my heavily modified version of your **mobile_app** demo: https://github.com/rydmike/mrnavdemo

It includes theme mode and theme toggling, and uses simple Riverpod state providers. It also uses Riverpod for the app state you used Provider for in the original demo. Main is looking like this:


```dart
class MyApp extends ConsumerWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    return MaterialApp.router(
      title: 'Routemaster Demo',
      debugShowCheckedModeBanner: false,
      theme: watch(lightThemePod).state,
      darkTheme: watch(darkThemePod).state,
      themeMode: watch(themeModePod).state,
      routeInformationParser: RoutemasterParser(),
      routerDelegate: RoutemasterDelegate(
        observers: [TitleObserver()],
        routesBuilder: (BuildContext context) {
          final bool _isLoggedIn = watch(isLoggedInPod).state;
          final bool _showBonusTab = watch(showBonusTab).state;
          // We swap out the routing map at runtime based on app state
          debugPrint('routesBuilder called!');
          return _isLoggedIn
              ? _buildRouteMap(_showBonusTab)
              : loggedOutRouteMap;
        },
      ),
    );
  }
}
```


It now seems to rebuild everything correctly as themes, theme mode are updated. Of course when you toggle adding the "bonus" page, then screens are rebuilt (state reset), but that is expected. 

It does call `routesBuilder` quite often though, like everytime it rebuilds MaterialApp.Router when e.g. the `themoMode` or `theme` is changed, but the screens themselves are not rebuilt, so that part is OK. Not sure what the overhead of the `routesBuilder` call is, if siginificant at all. The demo app does seem to be a bit more sluggish when it it comes to theme change animations, than it is with other none Nav2 approaches, but maybe that is just the nature of the beast, or maybe I'm imagining it, some experiments and verifications needed to be sure, but it probably does not matter,

Recorded demo:
https://user-images.githubusercontent.com/39990307/118510580-c1f4d900-b739-11eb-82df-868031d866d3.mov

**Comment by tomgilder** [comment]
@rydmike thank you! Yes, it'll rebuild whenever the App rebuilds. 

I don't think that will be _that_ big an issue performance-wise. It can be worked-around by caching the `RoutemasterDelegate`. Also only creating the `RouteMap` objects once will help with perf.

I think it's reasonable to say that for most apps, the top-level `App` won't rebuild that often, so I'm not overly concerned with this, but let's see 😁

**Comment by rydmike** [comment]
I agree.
Toggling between dark/light mode is probably the most common case, and of course if you allow for dynamic in-app customization/selection of the active theme, say eg for different color schemes, like in the above demo. But even in those cases it is not done that often, so probably OK... 👍🏻 

Nice fix! 😃
