### ISSUE TITLE
Pages don't get rebuilt when `PageStackNavigator` rebuilds

### ISSUE THREAD

**Issue by tomgilder** [tomgilder/routemaster#112]
Currently, when a `PageStackNavigator` rebuilds, the `Page` objects from the associated `PageStack` are never recreated.

This can lead to situations where the widget tree unexpectedly doesn't update.

This should either be well documented, or the `Page` objects should be updated when a `PageStackNavigator` rebuilds.

**Comment by tomgilder** [comment]
This is documented here for now: https://github.com/tomgilder/routemaster/wiki/Page-rebuilding

It's a difficult problem to solve...

**Comment by rydmike** [comment]
Like you wrote as well in the docs, if you use a state management solution in your app, and the content rebuilds bases it its changes, this might not be such a common or big issue.

Good that documented it. Trying to think of when it would be a big problem the way it is now. Hmm...🤷🏻‍♂️

**Comment by tomgilder** [comment]
I'm kinda going round in circles as to whether this is a bug or a feature 😁 

In some ways, it's good - it aids with performance. Only individual pages rebuild, rather than the entire stack below them.
But then, it's already confused some people, and I understand why.

But I've also noticed there are quite a few places with Flutter itself acts like this.

For now I'm going to not go into this further, and leave it for post-v1.0.

**Comment by tomgilder** [comment]
I've decided this is Just How Routemaster Works.

I've documented it on the FAQs.
