### ISSUE TITLE
Add easier way to get current router path

### ISSUE THREAD

**Issue by RedTech64** [tomgilder/routemaster#113]
I'm using a drawer in an IndexedPage that is visible on certain nested pages. When I try to use `RouteData.of(context)` in the IndexedPage to get the query paramethers I only get the route of that page. For example, if the current path is `/dashboard/orders?id=1`, it would return `/dashboard` Is there some way I can access the actual path no matter where I am?

**Comment by tomgilder** [comment]
Hi, I realise this is hilariously long, but you can get the global current path via this:

`Router.of(context).routeInformationProvider.value.location`

With null-safety it's `Router.of(context).routeInformationProvider!.value!.location`

Currently there's no Routemaster-specific way of getting the global query parameters, but this is something I've been thinking of adding.

Can I ask why you need to get the query parameters from the dashboard page?

**Comment by RedTech64** [comment]
@tomgilder Thanks I'll use that.

I was trying to use the drawer on the Scaffold on the dashboard page as a way to filter items shown on the sub page. I was tracking the filter parameters via query parameters.

**Comment by tomgilder** [comment]
Hi @RedTech64 I'm adding a much easier way to get the current path: `Routemaster.of(context).currentRoute`
