### ISSUE TITLE
mobile_app demo doesn't stay logged in when manually changing URL

### ISSUE THREAD

**Issue by rydmike** [tomgilder/routemaster#114]
In the routemaster bundled example **mobile_app** that uses:

`Routemaster.setPathUrlStrategy();`

When the app is built as a Web Chrome target in development mode, entering a URLs causes the app to reload entirely and it starts from login again.

If you remove `Routemaster.setPathUrlStrategy();` and keep the Flutter default silly (well none web standard anyway, nobody wants it) hash/number sign '#' strategy, it all works OK.

Can this silliness be fixed or is yet another Flutter Web SPA PWA "feature"? If that is the case, then the `Routemaster.setPathUrlStrategy();` is pretty useless (but not routemaster's fault of course) and then # just have to be used.

Perhaps it works with `Routemaster.setPathUrlStrategy();` if you deploy the **mobile_app** demo on a server. I did not try that yet. If so, that still means you would have to limit `Routemaster.setPathUrlStrategy();` to server deployments and cannot use it in dev mode.

**Comment by tomgilder** [comment]
If this is on Flutter master (and knowing you it probably is :grin:), they recently made a big change to Router that breaks Routemaster in many ways... fix coming

**Comment by rydmike** [comment]
This was actually on latest stable **2.2.0**, since it works well enough for web now. But yes desktop on Windows has many issues that are only solved to some extent on master, so I do indeed use it a lot 😃  and some are not even there yet... 😬

**Comment by rydmike** [comment]
And thx for the info, I was not aware of the `Router` changes since I have not built up anything like this fabulous **routemaster** so I have not really used it that much. Link to changes/PR?

**Comment by tomgilder** [comment]
@rydmike thanks, will have a look at this tomorrow

This PR messed with Routemaster quite a bit: https://github.com/flutter/flutter/pull/82727

But actually it's made me realise there are better ways of doing things :-)

**Comment by tomgilder** [comment]
Oh, sorry, yeah, this has nothing to do with the Flutter changes, it's just because that app doesn't have any persistent state management and when you enter the URL it restarts the entire thing (out of my control).

**Comment by rydmike** [comment]
Thanks @tomgilder, that kind of works for a micro part of the the issue, so it does not really work.
And yes I see what you did, but it is not a solution that works in a larger scale, and ti can even be shown with the demo app why not.

The entire app still reloads when you enter a new url, you just stored into the session that it was logged-in, and should load in that state instead, but if you switch with URL entry from one route to another, the app reloads and past navigation and app state is lost, like eg all the scroll states and nested nav states.

**Example:** 
Build the mobile_app and:
1. Login
2. Navigate to "Notifications" tab, select tab "Two"
3. Navigate to "Search" - do the hero page nav test on it
4. Change page via url entry "/feed" Result: Feed page is loaded, but we can already see it was refreshed and all SPA state was lost.
5. Click navigate to "Search" -> **Result:** Back on Test hero page **Expected**: Should have been on Hero page
6. Click navigate to "Notification" -> **Result:** Back on tab "One" page **Excepted** Should have been on tab "Two" page.

If you comment:

```dart
void main() {
  // Routemaster.setPathUrlStrategy();
  runApp(MyApp());
} 
```

Rebuild and do this this test with the "hash" in use. It all works as expected, also without storing the login state into web session storage, that you added.

---

Why is this? Is there anything that can be done about it for Flutter Web URL navigation so we can have "normal" and correctly working URLs without generally rejected "#" in it? 

Like I mentioned before, I did not try to deploy it to a server to see if it makes any difference, like eg even just GitHub Pages, perhaps it works then? Perhaps the WEB server can know the domain and main SPA path was not changed and not reload the app?

The problem seems of course to be that with the path url strategy, as soon as you make even one edit to the URL, the app is reloaded, but with the hash version, you can edit whatever is after the "#" without the SPA Web app reloading and loosing all state.

If it is only the Flutter Chrome mode that suffers from this with `setPathUrlStrategy` then one can of course work in dev mode without and deploy with it. If so might be good to explain this in the docs, and perhaps team Flutter could do something about it so it works in dev mode. That is all speculative of course, because I did not even test yet if it works when using `setPathUrlStrategy` going to try it. Hold on...

**Comment by rydmike** [comment]
OK @tomgilder I just built and deployed two version of the **mobile_app** on GitHub Pages.
Just built them from your main branch.

**The Hash URL version is here:**
https://rydmike.com/tgmobileapph
It should launch without entering the hash as apart if the first entry URL and then resolve to:
https://rydmike.com/tgmobileapph/#/

**The Path URL version is here:**
https://rydmike.com/tgmobileapp
It launches and with that URL entry and then resolves to:
https://rydmike.com/tgmobileapp/

So far all good...

Navigation on both work a**s long as you don't enter any URL.**
However, as soon as you enter a URL on the **path URL version** it breaks, it does not work at all, it always gives a 404 page.

The Hash URL version, works as it should.

---

Both builds were made with stable 2.2.0, release mode and canvaskit only.

**Comment by tomgilder** [comment]
There's nothing you can do about it - it's how web browsers work. They have to re-request the URL from the server when you enter a new one, so the app has to restart. It's nothing to do with Flutter, or Routemaster.

**Comment by tomgilder** [comment]
To make going directly to https://rydmike.com/tgmobileapp/feed load the app then you need to configure the web server to return the app from https://rydmike.com/tgmobileapp/_<anything>_ with some kind of wildcard routing. 

The app would still reload if you're on the app and manually enter a new URL. 

This is why Flutter defaults to the hash strategy - might be a bit ugly it's a lot easier to use.

**Comment by rydmike** [comment]
I have also seen a mention somewhere of some setup you have to make on servers to make none hash SPAs apps work as they should, when not using hash URL, but can' recall where now.

If it does not work and can't be made to work, it makes the none hash version totally useless and nonviable for Flutter apps, there is just no point with the path url then.

**Comment by tomgilder** [comment]
The non-hash version isn't totally useless, there's just a tradeoff.

I would argue users will very rarely navigate to myapp.com/pageone and manually change the URL to e.g. myapp.com/pagetwo, so it isn't often a problem, as long as the app can restore enough of its state.

**Comment by rydmike** [comment]
Yeah that won't work for our use case. The state must be kept, too much of it to store it all in the session, and darn tricky with all scroll positions and all nested navs. Also a reload of the entire app when the url is entered is not good UX either, too slow. The hash version does not reload anything when you enter URLs after the hash, everything just works as it should.

The path url strategy might work better with Firebase hosting than GitHub Pages, at least when they are in sub folders like I did above. Maybe, not sure yet. 

I just read that on Firebase hosting you can configure a hosted app as an SPA and it then always serves index.html regardless of what extra URLs you enter, so that might work better, if it also know when not to serve the page index.html, wish it might do, since it has the base url and knows it has been served and can see it has not changed, might work.

However, if it serves index again when you change the url, even if it is only the part after the apps base URL, then that does not work either. I might try a Firebase SPA deployment later out of curiosity later just to try this. Have not deploys a SPA to Firebase before, so it might be interesting just for that reason as well to try it.

For now though I'll stick to hash # urls in flutter Web I guess.

Thanks for the help Tom!  💙
