### ISSUE TITLE
FloatingActionButton does not work with bottom tabs

### ISSUE THREAD

**Issue by tahesse** [tomgilder/routemaster#116]
Hey,
first of all thank you for this awesome package!
I am currently trying to build and app that has a bottom tab bar and on some pages a `FloatingActionButton`. However, the bottom tab bar overlaps the `FloatingActionButton`:
![image](https://user-images.githubusercontent.com/13452321/119386285-96d53100-bcc7-11eb-9d1a-8a8cc58bba29.png)

I followed your code example from: https://pub.dev/packages/routemaster#cupertino-tabs

Are there any best practices from your side?

**Comment by tomgilder** [comment]
Hi, thanks for the kind words! Are you able to share a larger code sample? This doesn't look like a problem with Routemaster, just a standard Flutter widget issue.

Is the `FloatingActionButton` wrapped in a `Scaffold` in that page?

**Comment by tomgilder** [comment]
Hi @tahesse I'm pretty sure this isn't a problem with Routemaster so I'm closing this for now.

I suspect you're missing either a `Scaffold` or `SafeArea` widget. Please let me know if you have more info and I'll be happy to reopen it.

**Comment by tahesse** [comment]
Thank you @tomgilder. I followed https://github.com/tomgilder/routemaster#cupertino-tabs from the README.md to have CupertinoTabs in the bottom of my application. On another route, e.g. `/feed` I had to wrap the `FeedPage`'s `Scaffold` in a `SafeArea` if I wanted to use a floating action button there. Thank you so much! Solved. 👍🏻
