### ISSUE TITLE
No hero animations

### ISSUE THREAD

**Issue by ntoljic** [tomgilder/routemaster#126]
While updating to 0.9.0 I saw in the changelog that `PageStackNavigator` no longer comes with a `HeroControllerScope`.
I therefore switched from `RoutemasterDelegate` to `RoutemasterDelegate.builder` with the following `navigatorBuilder`:

```dart
navigatorBuilder: (BuildContext context, PageStack stack) {
  return HeroControllerScope(
    controller: MaterialApp.createMaterialHeroController(),
    child: PageStackNavigator(stack: stack),
  );
},
```

Unfortunately, hero animations do not work with this setup. I tried this in a simple test app with two routes ('/' and 'test') and pushing between them.

Do I need to specify a different kind of controller?

**Comment by tomgilder** [comment]
Hi, thanks for filing an issue.

If you're using `MaterialApp` then you shouldn't need to use `RoutemasterDelegate.builder`. Hero animations in the top-level Navigator should automatically work as `MaterialApp` creates a `HeroController` for you.

Here's a complete app that shows this:

```dart
import 'package:flutter/material.dart';
import 'package:routemaster/routemaster.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationParser: const RoutemasterParser(),
      routerDelegate: RoutemasterDelegate(
        routesBuilder: (context) {
          return RouteMap(
            routes: {
              '/': (_) => MaterialPage(child: PageOne()),
              '/two': (_) => MaterialPage(child: PageTwo()),
            },
          );
        },
      ),
    );
  }
}

class PageOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Hero(
              tag: 'hero',
              child: Container(height: 50, width: 50, color: Colors.red),
            ),
            ElevatedButton(
              onPressed: () => Routemaster.of(context).push('/two'),
              child: Text('Push'),
            )
          ],
        ),
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Hero(
          tag: 'hero',
          child: Container(height: 100, width: 100, color: Colors.red),
        ),
      ),
    );
  }
}
```

If you're have nested a `PageStackNavigator`, that's when you'll need to wrap them in a `HeroControllerScope` for heroes to work.

Please let me know if you're still having problems.

**Comment by ntoljic** [comment]
Thanks for the quick response. Indeed, reverting to a regular `RoutemasterDelegate` fixed it. 😃
