### ISSUE TITLE
Pushing page resets stack

### ISSUE THREAD

**Issue by RedTech64** [tomgilder/routemaster#139]
I think this might be user error on my part, but I'm experiencing this problem when pushing more than one page with an `IndexedPage`. 

So if I'm on a tabbed page `/orders` and then I push `/order/1` and I go back, it stays on the `/orders` page as expected. But, if I go one further and go from `/order/1` to `/order/1/edit` and then go back, it resets and goes back to the first tab.

Is this a bug? Or is there something I'm doing wrong here?

Here is a visual of what is happening. You can see how it goes back to the first tab on the left only when I go two pages deep.
![chrome-capture](https://user-images.githubusercontent.com/12768272/121210585-67830000-c841-11eb-8cfb-5ec13218a502.gif)

**Comment by tomgilder** [comment]
Thanks for the report, will investigate asap

**Comment by tomgilder** [comment]
I believe this is the same issue as #142 - should have a fix out tomorrow.

**Comment by tomgilder** [comment]
Hi @RedTech64, just published 0.9.4-dev1 on pub.dev, can you see if it fixes this please?

**Comment by RedTech64** [comment]
It is fixed on 0.9.4-dev1. Thank you!

**Comment by tomgilder** [comment]
Thanks, will push to stable once I've written tests.
