### ISSUE TITLE
Can't use ternary operator to return different page types

### ISSUE THREAD

**Issue by bdremynoel** [tomgilder/routemaster#140]
Currently, with v0.9.3, this route definition is not possible:

```dart
'/books/:id': (route) {
  final id = RouteUtils.asInt(route.pathParameters['id']!);

  return (id != null)
      ? TabPage(child: BookPage(id: id), paths: [...])
      : NotFound();
},
```

`The return type 'RouteSettings' isn't a 'Page<dynamic>', as required by the closure's context.`

**Comment by tomgilder** [comment]
Thanks for the report, will release a hot fix for this, hopefully tomorrow.

**Comment by tomgilder** [comment]
@bdremynoel this pattern should work in the meantime:

```dart
if (id == null) {
  return NotFound();
}

return TabPage(child: BookPage(id: id), paths: [...]);
```

**Comment by tomgilder** [comment]
I don't really understand what's going on here with Dart - this pattern is fine without null safety enabled, but won't compile with it.

I've filed an issue to get clarification before making a change to Routemaster here: https://github.com/dart-lang/sdk/issues/46333

In the meantime you can use `if` instead of the ternary operator.

**Comment by bdremynoel** [comment]
Yes, it's ok, there's no reason to change the template of TabPage and associates.

**Comment by tomgilder** [comment]
I think the solution here is to change `PageBuilder` to return `RouteSettings`, but then check at runtime that it's a `Page`.

That could lead to runtime exceptions if you tried to return something other than `Page`, but at least there isn't any other object that extends from `RouteSettings` in Flutter.

Really annoying limitation of Dart :-/
