### ISSUE TITLE
How to push full screen page on path of tab page?

### ISSUE THREAD

**Issue by bdremynoel** [tomgilder/routemaster#141]
```dart
'/ei': (route) {
  return TabPage(
      child: MyPage(),
      paths: ['res'],
  );
},
'/ei/res/:id': (route) {
   // This route automatically nested but I don't want to.
},
...
```

`res` tab page shows list, the other route `'/ei/res/:id'` is for detail. I need to get it full screen to avoid user navigation mistake when editing data.
- Changing route prefix is not an option, since I need deep linking too.
- Can't be anonymous either...

Any way to achieve this?

**Comment by tomgilder** [comment]
Hi, you need to change the path of the other page to _not_ start with `/ei/res`, because 'red' is a path under `TabPage`.

For instance `/ei/detail/:id` should work.

**Comment by bdremynoel** [comment]
But in this case, I won't stack the listing before the detail page. How can I have both ?

**Comment by tomgilder** [comment]
Sorry, I don't really understand your question. 

Could you write out what you're wanting the page and navigation structure to be?

**Comment by bdremynoel** [comment]
`/ei/res` => shows listing (from tab)
`/ei/res/:id` => shows detail page

If I navigate to `/ei/res/:id`, the deep linking works perfectly without doing anything, `/ei/res` tab is triggered and `/ei/res/:id` after this.
My is concern is about nesting. `/ei/res/:id` is nested and I'm looking for a trick to get it as a fullpage.
I tried redirection but this broke `/ei/res` stacking too.

**Comment by tomgilder** [comment]
Hi @bdremynoel, was this also caused by the other issue, or a separate problem?

**Comment by bdremynoel** [comment]
It's more a missing (impossible?) feature than a problem here.
For now, we can't get full page on path of tab page (with bottom bar).

**Comment by RastislavMirek** [comment]
My workaround in this scenario is simply not using Routermaster but directly calling Navigator.of(context, root: true).push(...). That works but the entire flow inside that full screen route will be exempt from Routemaster (not ideal of course).

**Comment by tomgilder** [comment]
Sorry, I'm not understanding what's not implementable here.

Are we talking about a fullscreen dialog?

Any chance of a screenshot of what you're wanting to achieve?

**Comment by tomgilder** [comment]
Without more information I'm afraid I can't do anything more here. I don't understand what feature isn't implemented, sorry.

@bdremynoel if you can provide an example with more info I'll be happy to reopen.

**Comment by RastislavMirek** [comment]
Hi Tom, I am not author of the issue but I believe I understand what he is requesting and I agree it is an important feature missing. Or perhaps this can be done already but we do not know how, so we would love the documentation to guide us. 

Basically, he wants to create a fullscreen page (via `'/tab1/somePath': (_) => CupertinoPage(child: content, fullscreenDialog: true),`) but that page is inside a tab bar e.g.`CupertinoTabBar`. In another words, it should push over the `/tab1` which is a home page of the first tab. However, because each tab has its own nested navigator, that does not include the tab bar, the tab bar will be visible over such full screen page. 

So we need a way how to open a full screen dialog that covers the tab bar as well but at the same time, when it is dismissed it shows a route that is possibly inside navigator nested within a tab bar again. If such way exists, please add it to documentation.

**Comment by tomgilder** [comment]
@RastislavMirek thanks for the clarification, does this example achieve this?

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:routemaster/routemaster.dart';

void main() => runApp(MyApp());

final routes = RouteMap(
  routes: {
    '/': (_) => CupertinoTabPage(
          child: HomePage(),
          paths: ['feed', 'settings'],
        ),
    '/feed': (_) => MaterialPage(child: FeedPage()),
    '/feed/profile/:id': (_) => MaterialPage(child: ProfilePage()),
    '/settings': (_) => MaterialPage(child: SettingsPage()),
    '/pop-up': (_) => CupertinoPage(
          child: CupertinoPageScaffold(
            navigationBar: CupertinoNavigationBar(
              middle: Text('Fullscreen dialog'),
            ),
            child: Container(),
          ),
          fullscreenDialog: true,
        ),
  },
);

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: RoutemasterDelegate(routesBuilder: (_) => routes),
      routeInformationParser: RoutemasterParser(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final tabState = CupertinoTabPage.of(context);

    return CupertinoTabScaffold(
      controller: tabState.controller,
      tabBuilder: tabState.tabBuilder,
      tabBar: CupertinoTabBar(
        items: [
          BottomNavigationBarItem(
            label: 'Feed',
            icon: Icon(CupertinoIcons.list_bullet),
          ),
          BottomNavigationBarItem(
            label: 'Settings',
            icon: Icon(CupertinoIcons.search),
          ),
        ],
      ),
    );
  }
}

class FeedPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(middle: Text('Feed')),
      child: ListView(
        children: [
          CupertinoButton(
            onPressed: () => Routemaster.of(context).push('profile/1'),
            child: Text('Push profile page'),
          ),
          CupertinoButton(
            onPressed: () => Routemaster.of(context).push('/pop-up'),
            child: Text('Show fullscreen dialog'),
          ),
        ],
      ),
    );
  }
}

class ProfilePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('Profile'),
      ),
      child: ListView(
        children: [
          CupertinoButton(
            onPressed: () => Routemaster.of(context).push('/pop-up'),
            child: Text('Show fullscreen dialog'),
          ),
        ],
      ),
    );
  }
}

class SettingsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(middle: Text('Settings')),
      child: Container(),
    );
  }
}
```

**Comment by RastislavMirek** [comment]
> @RastislavMirek thanks for the clarification, does this example achieve this?

Yes, it does (only tied with https://flutlab.io/ide), thank you! 

It would be great if this could be documented somehow, but IMO this may be too specific to include in README. Perhaps, it is time documentation is structured between multiple files .md that are linked from README. Also, Github has a (quite new) feature that allows you to create beautiful,  multipage documentation that is quickly becoming kind of standard for open source.

**Comment by RastislavMirek** [comment]
As a side note this solution, while elegant has one problem - the path should ideally be something like `/feed/profile/1/pup-up` not just `/pop-up` when the full screen dialog is shown over page `/feed/profile/1` (this is probably why I did not think of this solution). 

While this is not critical IMO, it prevents e.g. properly deep linking to such state of the app (when the dialog is displayed over `/feed/profile/1`). Also, it would be cool if that's what is displayed in browser URL bar with Flutter web - although this usage pattern comes from iOS, so I'd expect mostly mobile-first apps ported to web to deal with that.

**Comment by tomgilder** [comment]
Great, I'll add this to the readme. 

And yes, I agree, it would be great to have the option to show the URL like that. But I have no idea how that work work 😁

**Comment by tomgilder** [comment]
Documented at https://github.com/tomgilder/routemaster/wiki/Path-hierarchy
