### ISSUE TITLE
How to integrate Firebase FirebaseAnalyticsObserver

### ISSUE THREAD

**Issue by fvisticot** [tomgilder/routemaster#148]
Firebase recommands to use the navigatorObservers not available with Material.router constructor
How to use Firebase Analytics with routemaster ?

`FirebaseAnalytics analytics = FirebaseAnalytics();

MaterialApp(
  home: MyAppHome(),
  navigatorObservers: [
    FirebaseAnalyticsObserver(analytics: analytics),
  ],
);`

**Comment by tomgilder** [comment]
Hi, there's a guide for analytics here: https://github.com/tomgilder/routemaster/wiki/Analytics

Please let me know if there's anything more you need than that.

If you really want to use `FirebaseAnalyticsObserver` you could do so like this:

```
class AnalyticsObserver extends FirebaseAnalyticsObserver
    implements RoutemasterObserver {
  AnalyticsObserver({@required FirebaseAnalytics analytics})
      : super(analytics: analytics);

  @override
  void didChangeRoute(RouteData routeData, Page page) {}
}
```

But I think this will only log screen names if you set a `name` on the page.
