### ISSUE TITLE
TabPage - paths with lazy initialization ?

### ISSUE THREAD

**Issue by bdremynoel** [tomgilder/routemaster#149]
Trying to lazy load sets of pages with `deferred as` directive to split js files.

Since paths are all triggered when arriving on this "tab page", all pages (i.e. js files) are loaded which is counter-productive with the given directive.

Also, I'm using it with TabBarView and there's 10 tabs... for now.

Will this be possible in the future ?

**Comment by tomgilder** [comment]
Hi, thanks for the issue - I'll take a look into it, I'd absolutely like this to possible.

Out of interest, do you know if the widgets are actually building, or is it just that the JS files are loading?

**Comment by bdremynoel** [comment]
I exposed the issue with web context but this is unrelated. All tab routes are called, at start, when using `TabPage`.

I load js file in the route like this, so yes, even in web target, `DashboardPage` will be loaded:
```dart
'/dashboard': (route) {
  return MaterialPage(child: FutureBuilder(
    future: dashboard.loadLibrary(),
    builder: (...)  { ... return dashboard.DashboardPage(); },
  );
},
```

**Comment by RastislavMirek** [comment]
> Hi, thanks for the issue - I'll take a look into it, I'd absolutely like this to possible.
> 
> Out of interest, do you know if the widgets are actually building, or is it just that the JS files are loading?

I really hope that the tab widgets are not loaded all at once...

**Comment by tomgilder** [comment]
@bdremynoel I believe I'm right in saying that `deferred as` won't split JS files, as deferred components are only [available on Android](https://flutter.dev/docs/perf/deferred-components).

**Comment by tomgilder** [comment]
Closing this in favour of #149

**Comment by bdremynoel** [comment]
This is the same idea as deferred components on Android platform. (Absolutly not the same tech behind though).
Here's a [ref](https://medium.com/flutter/optimizing-performance-in-flutter-web-apps-with-tree-shaking-and-deferred-loading-535fbe3cd674) on this feature on web platform.

On web platform, this feature is implicit since JS file loading is managed by the browser.

**Comment by tomgilder** [comment]
Interesting, thanks! Shame the Flutter docs on deferred loading don't mention web.

From an app developer's point of view it looks like the exact same Dart syntax, so let's tackle it all in #177
