### ISSUE TITLE
Custom animation for page transitions

### ISSUE THREAD

**Issue by johnkueh** [tomgilder/routemaster#151]
Is there a quick way to do this?
eg. [transitionDuration/buildTransition in VRouter](https://vrouter.dev/guide/Examples/Transitions)

Sorry, i am new to Flutter!

**Comment by tomgilder** [comment]
Hello, you can use the built-in Flutter methods to do this.

Either use [TransitionDelegate](https://api.flutter.dev/flutter/widgets/TransitionDelegate-class.html) or [extend Page](https://gist.github.com/johnpryan/6c32e848b0dc71bc07f7070a84383d23#file-nav2_snippet_5-dart).

See also [this article introducing Navigator 2.0](https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade).

However sadly `TransitionDelegate` is pretty complicated 😞 

Routemaster doesn't provide anything more than these built-in Flutter methods, but it's very possible I'll add easier ways to customise animation in the future.

**Comment by tomgilder** [comment]
Oh, plus you can use [PageTransitionsTheme](https://api.flutter.dev/flutter/material/PageTransitionsTheme-class.html). I think that would actually be my recommended way.

Here's an [article with nice examples](https://medium.com/flutter-community/page-transitions-using-themedata-in-flutter-c24afadb0b5d).
