### ISSUE TITLE
`TransitionDelegate` supplied to `Routemaster` is not called on `push` neither `pop`

### ISSUE THREAD

**Issue by RastislavMirek** [tomgilder/routemaster#152]
`RoutemasterDelegate` constructor takes a `transitionDelegate` parameter. I expect that this  should be a `TransitionDelegate<T>` that gets called for every `RoutemasterDelegate .push(String)` and `RoutemasterDelegate .pop()` to determine route transition.

However, when I add a breakpoint to the supplied `TransitionDelegate`'s `resolve(...)` method, that breakpoint is never hit. Transition delegate is simply ignored by Routemaster.

**Comment by RastislavMirek** [comment]
My bad - the delegate needs to be supplied to any nested `PageStackNavigator` as well

**Comment by RastislavMirek** [comment]
OK, I realised that the delegate needs to be supplied to any nested `PageStackNavigator` as well. This should be documented.

Still, the `transitioningDelegate` is not called for `pop()` calls so I do not know how to suppress pop animation. Any suggestions? The goal is to have a page that is pushed with animation but popped without it.

**Comment by tomgilder** [comment]
Hi, yeah, `TransitionDelegate` is really confusing, it doesn't allow for preventing animation on pops (at least as far as I'm aware). Navigation animations and Navigator 2.0 is just a mess, frankly.

I'll add to the docs to clarify it's only used for the top-level Navigator.

Here's how you can achieve what you want, with the default transitions on push and nothing on pop:

```dart
class NoPopAnimationPage<T> extends MaterialPage<T> {
  NoPopAnimationPage({required Widget child}) : super(child: child);

  @override
  Route<T> createRoute(BuildContext context) {
    return NoPopAnimationPageRoute<T>(page: this);
  }
}

class NoPopAnimationPageRoute<T> extends PageRoute<T>
    with MaterialRouteTransitionMixin<T> {
  NoPopAnimationPageRoute({
    required MaterialPage<T> page,
  }) : super(settings: page);

  MaterialPage<T> get _page => settings as MaterialPage<T>;

  @override
  Duration get reverseTransitionDuration => const Duration(milliseconds: 0);

  @override
  Widget buildContent(BuildContext context) {
    return _page.child;
  }

  @override
  bool get maintainState => _page.maintainState;

  @override
  bool get fullscreenDialog => _page.fullscreenDialog;
}
```

Then use `NoPopAnimationPage` in place of `MaterialPage`.

**Comment by RastislavMirek** [comment]
Thank you, this helps. I solved the issue in some other way (changed the navigation flow so that I do not need pop without animation). And in another occasion, when I needed to customize animation, so I had to write a custom subclass of `Page`, so I digged a bit into what you offered in your reply.

Still, I fully agree that transitions/animations are a mess in Navigator 2.0. Perhaps Routermaster could help on this front as well, consistently with an idea that it acts like "usability patch" to Navigator 2.0. To that end, I suggest including a "custom transition page" (`RoutemasterPage`?) with Routemaster, that would offer a simplyfied and flexible interface to specify transitions (separatelly for push & pop) and perhaps have other uses in the future. If that sounds interesting I would be willing to prepare a draft of such an API in a form of pull request, including documentation & maybe some tests (if I figure out how to propertly tests screen transitions).

**Comment by tomgilder** [comment]
Great! And yes, that's exactly what I'm planning to do, and I already have a prototype of it - will share the code soon.

Current API is below, but I also want to add an easy way to change the transitions per platform - I think a common need will be to disable animations on web (or desktop) but not on mobile.

**Push animation but no pop**
```dart
TransitionPage(
  child: ProfilePage(),
  pushTransition: PageTransition.cupertino,
  popTransition: null,
)
```

**Different push and pop animations**
```dart
TransitionPage(
  child: ProfilePage(),
  pushTransition: PageTransition.fadeUpwards,
  popTransition: PageTransition.cupertino,
)
```

**Totally custom animation**
```dart
TransitionPage(
  child: ProfilePage(),
  pushTransition: PageTransition(
    duration: const Duration(milliseconds: 300),
    transitionsBuilder: const CustomAnimationTransitionsBuilder(),
  )
)


```

**Comment by tomgilder** [comment]
Also probably an abstract builder class that you can subclass.

Then you can easily make a runtime choice at runtime as to what transition you want; potentially even accessing providers and so on:

```dart
class CustomPage extends TransitionBuilderPage<void> {
  CustomPage({required Widget child}) : super(child: child);

  @override
  PageTransition? buildPopTransition(BuildContext context) {
    if (kIsWeb) {
      return null;
    }

    return PageTransition.fadeUpwards;
  }

  @override
  PageTransition? buildPushTransition(BuildContext context) {
    if (kIsWeb) {
      return null;
    }

    return PageTransition.cupertino;
  }
}
```

**Comment by tomgilder** [comment]
Opened a new issue to discuss: #172
