### ISSUE TITLE
Allow redirect path to contain template wildcards, that would match original path wildcards

### ISSUE THREAD

**Issue by RastislavMirek** [tomgilder/routemaster#155]
It would be great to be able to define something like

```
    RouteMap(routes: {
        '/home/:carId': (_) => Redirect('/cars/:carId')
        // define some more path
    })
```

and then when calling `Routermaster.of(context).push('/home/123')` the route would be set to "/cars/123".  Currently, the resulting path is "/cars/:carId".

**Comment by tomgilder** [comment]
Good idea, thanks!

**Comment by RastislavMirek** [comment]
> Good idea, thanks!

NP. I actually need this in production so I can send pull request (with no tests) if you like.

**Comment by tomgilder** [comment]
That would be awesome! I'm happy to write tests

**Comment by RastislavMirek** [comment]
Deal. You will have it within 2 hours.

**Comment by RastislavMirek** [comment]
There it is. Sorry it's later than promised but to make up for it I also added unit tests and documentation.

**Comment by RastislavMirek** [comment]
> That would be awesome! I'm happy to write tests

There it is. Sorry it's later than promised but to make up for it I also added unit tests and documentation.

**Comment by tomgilder** [comment]
Merged, thanks!
