### ISSUE TITLE
Document route priority when multiple routes are matched

### ISSUE THREAD

**Issue by RastislavMirek** [tomgilder/routemaster#159]
It should be documented that a route without route parameters has preference over a route with route  preferences when matching. That is, if there is path with specified path segment in route map it is matched rather than the same path with a wildcard in that segment.

As a side note, it should be an error (or assertion) to specify 2 path like this in a route map:

```
...
'/home/:carId/detail': (_) => ...,
'/home/:userId/detail': (_) => ...
...
```

If it is not and error then it should be also documented that this leads to undefined behaviour (or how it behaves).

**Comment by tomgilder** [comment]
Thanks for the issue, I thought I'd added asserts for this case but apparently not 😁 

And yes, will add documentation - plus I haven't actually thought about this case and what makes sense, so the priority is purely accidental at this point. 

Do you think the current priority makes sense? Is it the right way round?

**Comment by RastislavMirek** [comment]
According to my usage experience path with wildcard (parameter) segment has lower priority than path that same segment explicitly specified. Unless it is just pure luck that it works this way in case of my routemap. In any case, it is definitely correct, and useful behaviour. Consider for example this routemap:

```dart
...
'/cars/statistics': (_) => ...
'/cars/:carId': (_) => ...
```

As expected, the last route has lowest priority, so when I call `Routemaster.of(context).push('/cars/statistics')` I correctly end up on car stats page not on an error page telling me that car with ID `statistics` does not exist. I'd suspect that many users already depend on this behaviour (including me). If it's not intentional then I suggest to make it intentional (add a test?) and documented.

**Comment by tomgilder** [comment]
Documented in README and tests added to make sure this doesn't break 😁

**Comment by RastislavMirek** [comment]
Thanks, very appreciated (I am confident that not only by me).
