### ISSUE TITLE
(Fix suggested/found) Section "Custom Animations" in Wiki/Routemaster Flutter scenarios points to an example file with an incorrect directory

### ISSUE THREAD

**Issue by Lucas-ZX-W** [tomgilder/routemaster#161]
Suggesting edits to the wiki section Wiki/Routemaster Flutter scemarios/Custom Animations with the information below:

This wiki section mentions a `FancyAnimationPage` example class in a linked file called routes.dart currently linked to:

[https://github.com/tomgilder/routemaster/blob/main/example/mobile_app/lib/routes.dart](url)

But with the current project structure, the directory above does not exist, instead, `FancyAnimationPage` is found in:

[https://github.com/tomgilder/routemaster/example/mobile_app/lib/main.dart](url)

with example usage on lines **109-111** and **197-216**.

**Comment by tomgilder** [comment]
Thanks, fixed
