### ISSUE TITLE
push and remove until missing

### ISSUE THREAD

**Issue by rutaba1** [tomgilder/routemaster#163]
Hi. I am trying to implement this using web and I want to pop all pages from route stack and push a new page. Same as Navigator's 1.0 pushAndRemove functionality. Any idea how would I be able to do that? 

Also, is there a way to access the page stack and check how many pages are there in the stack?

Thanks!

**Comment by tomgilder** [comment]
Hello, you cannot clear the back stack on the web - it's a limitation of the browser DOM, not Flutter or Routemaster.

The internal route stack is always determined by the URL, so going from `/one/two to `/three/four` will change the history stack to `three` and `four`. But users can always try to go back to previous URLs on the web.

I don't think you can currently publicly get the full route stack, but this is something I could quite easily add. 

It would be useful to know your use case for both the `pushAndRemove` functionality and looking at the current page stack?

**Comment by rutaba1** [comment]
@tomgilder Thanks for reply. So in my web app when user logs in it takes to a selection screen and then the main dashboard. The problem is when I click back button on browser from dashboard, it takes me to the login screen and when I click forward button it takes me to dashboard and I want to prevent user from going back from dashboard to login screen thats the reason I want to use pushAndRemove. 

Also, there is a navigation drawer on my app and If I change url path on search bar of browser it does take me to correct screen but the menu highlighted on navigation drawer does not get updated. So I want to access navigation stack and track through a provider as soon as new page is added in stack change the state of Drawer and highlight correct item.

**Comment by tomgilder** [comment]
@rutaba1 it sounds like you want to use different route maps for logged in and logged out users. 

See the example here: https://github.com/tomgilder/routemaster/blob/main/example/mobile_app/lib/main.dart#L50

Swapping the route maps based on login state will prevent users from going back to the login screen, as it will be inaccessible. 

You can have the dashboard and login screen both at the root path, and it'll switch pages when they log in.

I'm closing this for now, as `pushAndRemove` doesn't make sense with Routemaster's URL-based routing. Let me know if you have any further questions
