### ISSUE TITLE
Attempting to navigate to any specific, non-root URL results in a 404 Not Found Error from the web server ONLY in the release build

### ISSUE THREAD

**Issue by Lucas-ZX-W** [tomgilder/routemaster#168]
Hello! Here I have a Routemaster setup that is very similar to the example, with a TabPage as the root view, holding 2 TabViews as its sub-views, and one of the subviews (kde_list) goes to another view that's NOT in the TabPage:

I did include ```Routemaster.setPathUrlStrategy();``` to get rid of the `#` in the URL, which is curently a somewhat experimental feature, but the errors persists after removing it.

```
final RouteMap routes = RouteMap(
  onUnknownRoute: (route) {
    return MaterialPage(child: NotFoundView());
  },
  routes: {
    '/': (route) => TabPage(
          child: HomeTabView(),
          paths: ['/kde_list', '/about'],
        ),
    '/about': (route) => MaterialPage(child: AboutView()),
    '/kde_list': (route) => MaterialPage(child: KDEListView()),
    '/kde_list/kde_0_restarting_kde_connect': (route) =>
        FadeEaseInOutAnimationPage(child: KDE0RestartingKDEConnectView()),
  },
);

void main() {
  Routemaster.setPathUrlStrategy();
  runApp(
    MaterialApp.router(
      routerDelegate: RoutemasterDelegate(routesBuilder: (context) => routes),
      routeInformationParser: RoutemasterParser(),
      debugShowCheckedModeBanner: false,
    ),
  );
}
```

During testing (running to browser with ```Flutter run -d Chrome```), the website seems to behave exactly as expected, inclding entering a URL with a sub-directory manually to visit that page directly, BUT, occasionally and seemingly randomly, these errors appear:

```
======== Exception caught by Flutter framework =====================================================
The following message was thrown:
Could not navigate to initial route.
The requested route name was: "/about"
There was no corresponding route in the app, and therefore the initial route specified will be ignored and "/" will be used instead.

====================================================================================================

======== Exception caught by Flutter framework =====================================================
The following message was thrown:
Could not navigate to initial route.
The requested route name was: "/kde_list"
There was no corresponding route in the app, and therefore the initial route specified will be ignored and "/" will be used instead.

====================================================================================================
```
These errors seems to have no noticeable effect on the testing, ```flutter run -d Chrome``` website, so I just sort of brushed them off for a bit. However, after building the release version of the website with ```flutter build web``` and placing all the files in an nginx web server, an interesting behaviour was observed:

When just browsing and navigating through the website WITHOUT touching the URL, the URL updates accordingly and correctly based on what page is currently present. However, if those exact same URLs (that are sub directories such as ```address.com/about``` or ```address.com/kde_list``` or ```address.com/kde_list/kde_0_restarting_kde_connect```) were to be typed into the browser, a 404 Not Found error is encountered. Strangely still, despite the fact that the Flutter site did have its own ```NotFoundView()``` passed into the ```RouteMap```'s ```onUnknownRoute``` argument, the 404 page encountered was nginx's own default 404, indicating that it's not just that it cannot find the directory in the Flutter site/app, but the entire site itself.

I would likely be providing more information here in comments as I continue to test. Currently, despite the fact that I don't concretely know whether those errors shown were the problem, I think they are a strong factor in investigate.

Thanks for any help!

**Comment by tomgilder** [comment]
Hi, this isn't a Routemaster issue; your server configuration needs changing.

Your server needs to be configured to return the Flutter app from all paths, such as `address.com/about`.

When you manually change the URL in the browser, the browser sends a new request to `address.com/about`, which is returning 404 from the server.

I'll add this to documentations.

**Comment by Lucas-ZX-W** [comment]
Hi, I would just like to follow up on the "issue", I understand that it's not related to Routermaster itself but I think it's nonetheless useful for anyone looking to deploy Flutter web apps/sites.

I was able to redirect all incoming requests to Nginx to the root index.html using the following location block (and I believe it should be the only location block in the configuration file:

```
location / {
    try_files $uri $uri/ /index.html;
}
```

**However**, while this did function as intended, this also brought up a bit of a side-effect:

If I request ```address.com/about```, for example, nginx basically takes that URL and changes it into just ```address.com``` and put it back into the URL entry field. As such, despite the fact that the correct View in the Flutter app is reached, the URL shown is actually just ```address.com```, not the actual (Routemaster) URL of ```address.com/about```.

Only when I navigate, using the Flutter app itself, into another Routemaster URL does the URL field actually update to reflect the correct subdirectory, at which point if I go back to the ```about``` page by clicking around in the Flutter app, it would show the correct URL of ```address.com/about```.

I think that there could be 2 potential ways of solving this:

1) Have the Flutter app / Routemaster override the redirected, root URL from Nginx into the correct sub-directory upon loading the site. A quick and perhaps inefficient solution would be to have each URL .replace() or push() itself when it initializes? (and hence write the correct sub-directory URL to the URL field)?

2) Configure Nginx in a way that preserves the original requested URL subdirectory in the URL field but still actually goes to the root. I'm no Nginx (or any other web server) expert so I personaly don't even know if this is possible, let alone how to implement it.

I would like to ask how everyone else is going about with this problem.

Thanks!
