### ISSUE TITLE
Change Url in flutter web programatically or dynamically

### ISSUE THREAD

**Issue by rutaba1** [tomgilder/routemaster#173]
Hello. So I have a screen where my web app has list of expandable cards. My use case is, as I expand the any card by clicking on it, the url should update as well. Say my list screen is `/jobs` and when I expand any card in jobs screen the url should update to`/job/:job_id`. Similarly if I type in url `/job/:job_id`, the job card with that id should get expanded. 
Is there a way in route master to update urls programatically/dynamically?

**Comment by tomgilder** [comment]
Hello, the only way to update the URL is to `push()` or `replace()` to another path, and to pass the new `job_id` through to the page.

The URL must be in the routing map, you can't just update the browser's URL to something that isn't in the map.

Is there a reason that won't work in this case?

**Comment by rutaba1** [comment]
@tomgilder If I push a new page when expanding a card while being on the same page, won't It create two jobs pages in stack - one with job_is and one without job_id. And when back button of browser is pressed it would take user to jobs screen will collapses card rather than going back to any previous screen before jobs screen

**Comment by tomgilder** [comment]
Can't you just use `.replace()`?

**Comment by rutaba1** [comment]
I could but as I opened another [issue](https://github.com/tomgilder/routemaster/issues/163) that replace is not replacing the current page and I could still go back If clicking in browser back button.

**Comment by tomgilder** [comment]
You can forcibly report a new URL to the browser:

```dart
SystemNavigator.routeInformationUpdated(location: '/job/1');
```

But of course that won't work again if the user tries to load `/job/1`. 

I'm not really sure what this issue is asking for beyond what Routemaster provides, sorry, so I'm closing for now.

Please feel free to comment if you think there's missing functionality,
