### ISSUE TITLE
Release build of Routemaster web app incorrectly writes root URL to the address bar if the request is a subdirectory URL, but does display the correct Page

### ISSUE THREAD

**Issue by Lucas-ZX-W** [tomgilder/routemaster#175]
I've built and deployed a Routemaster web app, similar to the examples in this repo, to a web server running Nginx. Since the release built of the web app has everything in one folder/directory, I've configured Nginx to redirect all incoming requests to the root index.html using the following ```location``` block:

```
location / {
    try_files $uri $uri/ /index.html;
}
```

This make is possible to directly request a subdirectory URL, such as ```address.com/about```, and any 404 requests would display the web app's own 404 Page as defined in the ```onUnknownRoute``` argument to the ```RouteMap``` constructor.

However, according to [https://github.com/tomgilder/routemaster/issues/173#issuecomment-878320575](url), the only ways to update the URL of the web app is to call ```.push()``` to ```.replace()```, both of which are typically used by navigation elements as the user browses around the web app, and works fine in that regard.

However, does this mean that, with the Nginx redirect configuration, when someone try to request a subdirectory directly, such as ```address.com/about```, where no ```.push()``` or ```.replace()``` would be typically called since it was manually requested directly, despite the fact that it would display the correct ```about``` Page, the URL in the address bar would be overridden with the root ```address.com``` once the web app loads since nothing prompted the web app to display the correct subdirectory?

This is exactly the problem that I am facing. At first I thought it might be a problem with Nginx, but I've started to notice that it might be related to Routemaster/Flutter.

To understand why I believe that it's a Routemaster/Flutter problem, we have to understand the steps that the web app loads:

Step 1: Type ```address.com/about``` into browser address bar and press enter.

Step 2: The browser's progress bar goes to 100% very quickly, suggesting that the Nginx redirect is complete and that a connection to the index.html is established. **The address bar continues to show the original request of ```address.com/about``` after this is done.**

Step 3: A white screen is displayed as the Flutter web app takes its sweet time to load. **At this point, the address bar continues to show the original request of ```address.com/about```.**

Step 4: After a couple of seconds on the white screen, the Pages are actually loaded. **NOW, the address bar showing the correct requested subdirectory ```address.com/about``` is OVERRIDDEN with the incorrect root directory ```address.com``` instead**, despite the fact that the Page that's actually loaded is indeed the correct ```about``` Page.

This seems to suggest that it was the Routemaster/Flutter web app that, upon successfully loading itself, overrode the initial, correct subdirectory request URL of ```address.com/about``` with the incorrect root URL, ```address.com```.

If it was Nginx (or any web server I suppose) that was causing the problem, I believe that the override would take place much earlier on during step 2, before the progress bar of the browser actually goes to 100%, which is not the case here.

So now, we effectively have the ```about``` Page, which is supposed to have the ```address.com/about``` URL, correctly on the screen, but the URL displayed in the browser is ```address.com```, this means that upon refreshing the page, the browser would go back to the root directory instead. At this point, using any navigation element (that uses ```.push()``` or ```.replace()```) to go to another Page would make the displayed URL correct again, hence my speculation earlier on that it was the lack of ```.push()``` and ```.replace()``` that resulted from a direct subdirectory URL request that cause the Flutter app to incorrectly write the root URL to the browser address bar since it can only handle the situation where a subdirectory was reached via ```.push()``` and ```.replace()``` via navigation elements, NOT if it was reached directly from a subdirectory URL request.

Again, this is just a speculation based on my observations, I could be totally wrong about this. But I would like to bring this up nonetheless since it would be an important piece of information for anyone tying to deploy a Routemaster/Flutter web app.

**Comment by tomgilder** [comment]
Hello, I've tried to reproduce this by setting up Nginx with that configuration, but everything is working fine for me.

I used the [example bookstore app](https://github.com/tomgilder/routemaster/tree/main/example/book_store) and `setPathUrlStrategy()`, and I can load subpages such as `http://localhost:8080/book/1` and the page loads correctly and sticks on the correct URL.

But I agree from your description it does sound like a Flutter/Routemaster bug, but I'm afraid I'm not going to be able to do any more here without a reproduction case.

What browser are you seeing this behaviour on please?

**Comment by Lucas-ZX-W** [comment]
Thanks Tom, here are some more information that I found during further testing:

This is definitly a Routemaster/Flutter "problem" as I noticed that this also happens in the testing build (```flutter run -d chrome``` or just selecting a browser as a target in Android Studio and pressing the compile/run button) where Nginx is not involved at all. I was testing the release Nginx deployment in Safari when I write the original issue post but the test build was conducted in Chrome, so I don't think it's a browser dependent issue.

I would like to put this here early that despite that fact that I've provided most of the relevant code down below along with further explanation, since this is a deployed web app that we're talking about, simply go to [lucaswangzx.xyz](lucaswangzx.xyz) to see the issue in action. Try a sub-directory like [lucaswangzx.xyz/about](lucaswangzx.xyz/about), [lucaswangzx.xyz/kde_list](lucaswangzx.xyz/kde_list), or [lucaswangzx.xyz/kde_list/kde_0_restarting_kde_connect](lucaswangzx.xyz/kde_list/kde_0_restarting_kde_connect) and you'll see it get re-written to just the root [lucaswangzx.xyz](lucaswangzx.xyz) when the Flutter app itself finishes loading (in my testing it takes a couple seconds of white screen before that happens).

I noticed that **this issue seems to occur when the root View of the ```RouteMap``` is a ```TabPage()``` of some sort**, which is the case with my app (and not the [example bookstore app](https://github.com/tomgilder/routemaster/tree/main/example/book_store) that you tested with):
```
routes: {
  '/': (route) => TabPage(
        child: HomeTabView(),
        paths: ['/kde_list', '/about'],
      ),
  '/about': (route) => MaterialPage(
        name: "About Lucas' Archive",
        child: AboutView(),
      ),
  '/kde_list': (route) => MaterialPage(
        name: "KDE Articles, Lucas' Archive",
        child: KDEListView(),
      ),
  '/kde_list/kde_0_restarting_kde_connect': (route) =>
      FadeEaseInOutAnimationPage(
        child: KDE0RestartingKDEConnectView(),
      ),
},
```
To verify that this was the case, I made a single modification to the entire codebase, deleting the ```TabPage()``` at ```'/'```, resulting in the new ```RouteMap``` below:
```
routes: {
  '/about': (route) => MaterialPage(
        name: "About Lucas' Archive",
        child: AboutView(),
      ),
  '/kde_list': (route) => MaterialPage(
        name: "KDE Articles, Lucas' Archive",
        child: KDEListView(),
      ),
  '/kde_list/kde_0_restarting_kde_connect': (route) =>
      FadeEaseInOutAnimationPage(
        child: KDE0RestartingKDEConnectView(),
      ),
},
```
Now, when requested a subdirectory of ```rootaddress.com/about```, ```rootaddress.com/kde_list```, or ```rootaddress.com/kde_list/kde_0_restarting_kde_connect```, the problem is gone and the URL stays correct.

I should also mention that the root ```TabPage()``` contains a View that houses the ```Scaffold```, ```DefaultTabController``` and ```Tabbar``` for the ```TabView```. This effectively means that the Scaffold and the top ```AppBar``` visible in every single sub-view came from the View in the root ```TabPage()```. So technically, for all Views and sub-directories, both the View from ```'/'``` and whatever the view of their own sub-directory is are responsible for rendering parts of the screen.

Here are some summaries of the different views to hopefully make what was described above a bit more clear:

```TabPage()``` at root ```'/'```:
```
class HomeTabView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final TabPageState tabPage = TabPage.of(context);

    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.teal,
      ),
      home: DefaultTabController(
        length: 2,
        child: Scaffold(
          appBar: AppBar(
            title: Row(
              children: [
                   // Top Title Content
              ],
            ),
            actions: [
                   // Top action buttons
            ],
            bottom: TabBar(
              controller: tabPage.controller,
              tabs: [
                  // TabBar Buttons
              ],
            ),
          ),
          body: TabBarView(
            controller: tabPage.controller,
            children: [
              for (final stack in tabPage.stacks)
                PageStackNavigator(stack: stack),
            ],
          ),
        ),
      ),
    );
  }
}
```
```/about``` is just a ListView:
```
class AboutView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      padding: const EdgeInsets.all(30),
      children: [
          // About View content
      ],
    );
  }
}
```
```/kde_list/kde_0_restarting_kde_connect``` has its own scaffold which would go underneath the main ```TabBar``` from root so it can have its own title and back button:
```
class KDE0RestartingKDEConnectView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: Row(
          children: [
                 // AppBar title content
          ],
        ),
      ),
      body: ListView(
        padding: const EdgeInsets.all(30),
        children: [
               // Body content
        ],
      ),
    );
  }
}
```
Thanks!

**Comment by tomgilder** [comment]
Thanks for the sample code, really useful, I've reproduced this. Does seem to only happen with a `TabBar`.

Are you also seeing this exception in your debug console?

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:174:12
_hasSerialCount(currentState)
is not true
```

**Comment by tomgilder** [comment]
Ahhh... you have an extra `MaterialApp` in your `HomeTabView` - removing that should fix it. You shouldn't have two `MaterialApp` widgets in the same app.

**Comment by Lucas-ZX-W** [comment]
Oh, thanks Tom! I have a habit of including a ```MaterialApp``` in the top-level View (in this case the View where the Tab Controller resides) and didn't realized that ```MaterialApp.router()``` is itself a ```MaterialApp```.
