### ISSUE TITLE
[Proposal] Improve the path strategy usage in `SystemNav`

### ISSUE THREAD

**Issue by navaronbracke** [tomgilder/routemaster#185]
Currently `routemaster` has a dependency on `flutter_web_plugins`.

It also has a class called `SystemNav`, which provides an option to set the path strategy (useful on web).

However `routemaster.dart` does not export `src/system_nav.dart`, which prevents library consumers from using it.
Secondly, on mobile the methods `setPathUrlStrategy()` and `setHashUrlStrategy()` return `UnsupportedError`, despite having a void return type. The official docs also mention just using an empty body on mobile. I.e. `{ // No-op on mobile }`

I propose that the methods `setPathUrlStrategy()` and `setHashUrlStrategy()` no longer return an exception. Instead use a No-op comment, explaining that these methods are only useful on web.

Secondly, export the `SystemNav` class (or at least `setPathUrlStrategy()` and `setHashUrlStrategy()`) from `src/system_nav.dart`

**Comment by tomgilder** [comment]
Hi @navaronbracke, thanks for the issue, what are you wanting to do that you can't already?

You can call `Routemaster.setPathUrlStrategy()` to use the path strategy, otherwise it defaults to hash.

Are you wanting to use a custom strategy?

**Comment by navaronbracke** [comment]
Aha, I didn't see that. I expected to have to use the `SystemNav` class directly. Probably missed this line in the public Routemaster API.
