### ISSUE TITLE
Unnecessary navigation with subroutes

### ISSUE THREAD

**Issue by TomasWeg** [tomgilder/routemaster#186]
I don't know if the feature can be disabled or routemaster was developed with that in mind, but when you have the following route, for example: 

`/users/inspect/:id`

Being `/users` another registered route in `RoutemasterDelegate.routesBuilder`, when you want to navigate to `/users/inspect/:id`, it will always navigate first to `/users`, and, in my case, causes unnecessary api calls.

**Comment by tomgilder** [comment]
Hi Tomás, this is just how Routemaster works (and I believe every other routing package). You should expect ancestor routes to build when navigating to a child route.

To avoid doing API calls on pages that aren't top of the stack, you can check `ModalRoute.of(context)!.isCurrent`.

Hope that helps, closing for now, let me know if you have any other questions.
