### ISSUE TITLE
Transition between route maps

### ISSUE THREAD

**Issue by josh-burton** [tomgilder/routemaster#191]
It seems the supported way of handling login with routemaster is swapping the route map based on the logged in state.

Currently this results in an instant switch to the new logged in route. How could we add a transition between the routes?

**Comment by tomgilder** [comment]
Hi, thanks for the question.

Providing different keys should make the transition happen, so for your logged out map:

`'/': (_) => MaterialPage(child: LoginPage(), key: ValueKey('login')),`

And then logged in map:

`'/': (_) => MaterialPage(child: HomePage(), key: ValueKey('home')),`

Let me know if that works for you

**Comment by tomgilder** [comment]
Closing for now - let me know if you need more info and I'll reopen

**Comment by gbmarcos** [comment]
> Hi, thanks for the question.
> 
> Providing different keys should make the transition happen, so for your logged out map:
> 
> `'/': (_) => MaterialPage(child: LoginPage(), key: ValueKey('login')),`
> 
> And then logged in map:
> 
> `'/': (_) => MaterialPage(child: HomePage(), key: ValueKey('home')),`
> 
> Let me know if that works for you

ya me estaba patiendo la cabeza, el que abrió el issue no te agradeció pero yo si, lo que en español...jjj
