### ISSUE TITLE
routesBuilder doesnt rebuild routes with bloc state management

### ISSUE THREAD

**Issue by nbourdin** [tomgilder/routemaster#200]
Hello

I use bloc state management and when i try to swap routes in a case of login, i note that the RoutemasterDelegate does not call the `routesBuilder(context) `method.

I made a fork of the projet, in order to reproduct the behavior on the [deeplink example ](https://github.com/nbourdin/routemaster/commit/04ae5e4e9d7883713f13635cc11969cfeda00590).

When i put the RoutemasterDelegate directly in the Material.route (without using a variable) it works...

Did you think the problem should come from the bloc lib or from the routemaster lib?

I'm not a pro issuer, so feel free to ask me some details.

**Comment by tomgilder** [comment]
Hey @nbourdin, thanks for the question. 

I would guess your bloc isn't rebuilding properly, but I'm not sure. Thanks for the repo, will have a look into it when I get time.

**Comment by nbourdin** [comment]
Yes, that's what I thought the first time, but I see that it passes through the builder(..) method of the BlocBuilder...
Thank you so much for your time
