### ISSUE TITLE
Using arbitrarily chained URLs

### ISSUE THREAD

**Issue by craigomac** [tomgilder/routemaster#205]
Thanks for the great library! One detail seems to elude me: if I have some page that pushes an arbitrary number of other pages of related types or even its own type, how can I declare that in my routes?

Take this minimal example:

```
routes: {
  '/author/:id': (data) => AuthorPage(data),
  '/book/:id': (data) => BookPage(data)
}
```

An author page would list their books—and a book page might link to suggested authors of similar works. So in my app I might have a navigation stack of multiple authors and books. For example the URL could be `/author/1/book/5/author/3/book/10/book/20` (of course if this were a website this stuff wouldn't need to be in the URL: it's a history stack. But for my app's purposes, the navigation stack *is* the history).

How can I keep pushing pages onto my navigation stack without having to specify fixed URL specifications of increasing length?

**Comment by craigomac** [comment]
Aha, it looks like the same issue flagged here with a possible solution: https://github.com/tomgilder/routemaster/issues/5#issuecomment-886228999.

**Comment by tomgilder** [comment]
Thanks @craigomac!

And yes this will be in the next version - you can have a look at PR #194 that has it

Would love any comments/reviews on it 😁
