### ISSUE TITLE
Routemaster.of(context).pop() returns false even though there is a route before the current route

### ISSUE THREAD

**Issue by navaronbracke** [tomgilder/routemaster#215]
I have encountered a weird bug with `Routemaster.of(context).pop()`.
It is never called in the following situation:

1) run the example app
2) press the forgot password button (/reset-password is pushed onto the routing stack)
3) observe that `Routemaster.of(context).pop()` returns false

I am using `routemaster: 0.10.0-dev2` (dev5 was released just now but it also happens there)

Example:
```
import 'package:flutter/material.dart';
import 'package:routemaster/routemaster.dart';

class LoginPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: const Text("Forgot Password"),
          onPressed: () {
            Routemaster.of(context).push("/reset-password");
          },
        ),
      ),
    );
  }
}

class ForgotPasswordPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: const Text("Back to first page"),
          onPressed: () {
            Routemaster.of(context).pop().then((result) {
              print(result); // This is false?
            });
          },
        ),
      ),
    );
  }
}

void main() {
  runApp(
    MaterialApp.router(
      routeInformationParser: const RoutemasterParser(),
      routerDelegate: RoutemasterDelegate(
        routesBuilder: (context) {
          return RouteMap(
            routes: {
              '/': (_) => const Redirect('/login'),
              '/login': (_) => MaterialPage(
                    child: LoginPage(),
                  ),
              '/reset-password': (_) => MaterialPage(
                    child: ForgotPasswordPage(),
                  ),
            },
            onUnknownRoute: (path) {
              return const Redirect('/login');
            },
          );
        },
      ),
    ),
  );
}
```

**Comment by tomgilder** [comment]
Hi @navaronbracke, thanks for the issue, but this is working as expected.

When you're on `/reset-password`, there is no page in the page stack before it, because `/` is a redirect. If `/` was an actual page, it would pop to it.

The `pop()` method pops the navigation stack of pages: it doesn't go back in history.

If you're wanting to go back to whichever page the user saw, there is now `Routemaster.of(context).history.back()` in 0.10.0-dev5.

I hope that helps you, please let me know if you have any more questions.

**Comment by navaronbracke** [comment]
@tomgilder Thanks for the clarification. I'll use `Routemaster.of(context).history.back()` instead.
