### ISSUE TITLE
Swapping Cupertino tabs route maps

### ISSUE THREAD

**Issue by matthewfx** [tomgilder/routemaster#234]
Hi,

Another issue with Cupertino tabs I've stumbled upon.

If we have two maps but both start with CupertinoTabPage

```
final tabs1Routes = RouteMap(
  routes: {
    '/': (_) => CupertinoTabPage(
          child: HomePage(),
          paths: ['/feed', '/settings'],
        ),

    '/feed': (_) => MaterialPage(child: FeedPage()),
    '/settings': (_) => MaterialPage(child: SettingsPage()),
    '/feed/profile/:id': (info) => MaterialPage(
      child: ProfilePage(id: info.pathParameters['id'])
    ),
  }
);

final tabs2Routes = RouteMap(
  routes: {
    '/': (_) => CupertinoTabPage(
          child: HomePage2(),
          paths: ['/login', '/pics'],
        ),

    '/login': (_) => MaterialPage(child: LoginPage()),
    '/pics': (_) => MaterialPage(child: PicsPage()),
  }
);
```

When we try to swap the first one for the second the app will show:
Page '/feed' wasn't found.

I've tried even using the same route names for tabs in the second route. For example the first tab route would be called 'home' in both maps. Then when on the first tab I can swap  but the first tab will remain the page defined in the first map...

Is there a way to do it?

Cheers,

mat

**Comment by hffmnn** [comment]
It should work by adding a `onUnknownRoute: (_) => Redirect('/'),` to the `RouteMap` definition.

**Comment by matthewfx** [comment]
@hffmnn that seems to be working although I need to admit that I would prefer if there was something not requiring to use of the` onUnknownRoute`. Anyways, thank you very much  Christian :)
