### ISSUE TITLE
RangeError (index) on mobile_app demo

### ISSUE THREAD

**Issue by decadentsavant** [tomgilder/routemaster#252]
I cloned the repo, retrieved packages, and ran the mobile_app in the example folder.

To reproduce error:
1. Launch app
2. Click "Log In"
3. Click on Settings tab
4. Toggle "Show bonus tab"
5. Click on Bonus! tab
6. Click on Settings tab

Note that on step 4, after toggling the switch, the Notifications tab is immediately highlighted while the UI still shows the settings information. The index doesn't ever seem to update to reflect a 5th option (index 4).

This is reproducible on both the Android and iOS emulators.

**Comment by tomgilder** [comment]
Fixed, thanks!
