### ISSUE TITLE
Issue with mobile_app example

### ISSUE THREAD

**Issue by HosseinYousefi** [tomgilder/routemaster#257]
## Steps to reproduce

1. Run the example 'mobile_app' from the examples of the package.
2. Login
3. Navigate to the settings tab
4. Enable the 'Show bonus tab' switch.

## Expected

We should remain on the settings page and the settings icon should still be highlighted.

## Actual

We do stay on the settings page but the highlighted icon in the bottom nav bar becomes the notifications one. Tapping on the now un-highlighted settings icon causes a range error (`RangeError (index): Index out of range: index should be less than 4: 4`
).

<img width="499" alt="Screenshot 2022-03-02 at 16 16 54" src="https://user-images.githubusercontent.com/9751815/156331817-bfbb21e6-9a1f-485c-a0e7-332a3c203765.png">

**Comment by HosseinYousefi** [comment]
This is a duplicate of #252

**Comment by tomgilder** [comment]
Thanks, closing as a duplicate
