### ISSUE TITLE
`popUntil` documentation seems wrong

### ISSUE THREAD

**Issue by knopp** [tomgilder/routemaster#271]
https://github.com/tomgilder/routemaster/blob/f3dec248e509cadb29716e91792c70f413b93c51/lib/routemaster.dart#L166-L171

The comment would be true if the method was called `popWhile`. The actual behavior is that `popUntil` keeps popping while the predicate returns `false`.

**Comment by tomgilder** [comment]
Ooops! Thank you, fixed 😁
