### ISSUE TITLE
How to pass arguments internaly without placing them in URL?

### ISSUE THREAD

**Issue by bambinoua** [tomgilder/routemaster#276]
The default `Navigator.push` procedure allows to pass `arguments` to route to handle them.
```dart
Navigator.push(context, 
  MaterialPageRoute(
    builder: (_) => Login(),
    settings: RouteSettings(
      name: '/login',
      arguments: 'Some message', // <-- I need this
    ),
  ),
);
```
 Is it possible to do the same in `routemaster`? For example I need to pass some message  to login screen (the reason why user see login scree) but I want to pass it internally via `arguments` and not via URL hash or something like this. Is it possible?

**Comment by nicolasmol** [comment]
Any explanation of this dumbthumb closure  ?
