### ISSUE TITLE
Do you plan to create a `NavigationBarPage` ?

### ISSUE THREAD

**Issue by yakitama5** [tomgilder/routemaster#279]
Do you plan to create a `NavigationBarPage` for the [NavigationBar](https://api.flutter.dev/flutter/material/NavigationBar-class.html) that appeared in Flutter 3.0?

I hope it can be used like `TabPage` or `CupertinoTabPage`.

**Comment by tomgilder** [comment]
Hello, good news, there's no need for one 😁 

`NavigationBar` doesn't require a controller, so you can use the existing `IndexedPage`.

I've added an example: https://github.com/tomgilder/routemaster/tree/main/example/navigation_bar
