### ISSUE TITLE
How to add title to tab page

### ISSUE THREAD

**Issue by Kings-Samuel** [tomgilder/routemaster#288]
Hi. How can we add titles to every tab with this package? Some other navigation packages provide this feature, We'll appreciateit if we can have it in Routemaster too.

**Comment by tomgilder** [comment]
Hello, use the build-in Flutter `Title` widget: https://api.flutter.dev/flutter/widgets/Title-class.html

```dart
Title(
   title: 'My Page Title',
   child: PageWidget(),
);
```
