### ISSUE TITLE
Issues with replacing root

### ISSUE THREAD

**Issue by videah** [tomgilder/routemaster#297]
I'm currently trying to achieve a flow that looks like this:
```mermaid
  graph TD;
     / -- User signs in -->/main;
    /main-->/main/settings;
    /main/settings -- User signs out --> /
```

Where `/` is a sign in page, upon successfully signing in `/main` should become root with no possibility of pressing a back button or sliding from the side to get back to the sign in page. `/` should only become root again once the user has signed out.

I assumed simply calling `Routemaster.of(context).replace("/main")` from `/` would give me the result I wanted but it still ends up being possible to go back from `/main` to `/` with an arrow appearing in the app bar. This is despite the route history not including `/`
```dart
RouteHistory(index: 0, canGoBack: false, canGoForward: false, history: [/main])
```

Is there something I'm missing? I've found this very easy to do with Navigator 1.0 but I'm struggling to do the same thing here.

**Comment by tomgilder** [comment]
Hi, Routemaster builds routes based on the URL.

If you have a route at `/` and `/main`, then navigating to `/main` will build both those routes and put them on the navigation stack.

You probably want to use two route maps, and change what page appears at `/` based on whether the user is logged in or not.
