### ISSUE TITLE
[BUG] Url is changing but page is not

### ISSUE THREAD

**Issue by batuhand** [tomgilder/routemaster#301]
This is a flutter web issue

I use a build route similar to his 

```
shop_admin_orders_path: (route) => NoAnimationPage(
          child: ShopAdminView(
            selectedBody: ShopAdminOrdersView(),
            headline: "Siparişler",
          )),
```
```
      shop_admin_products_path: (route) => NoAnimationPage(
          child: ShopAdminView(
            selectedBody: ShopAdminProductsView(),
            headline: "Ürünler",
          )),
```

So what I want to do is, only change the body widget of the screen when link changes.
If I directly go the links, there is no issue, but if I send the user with 
` onTap: () => Routemaster.of(context).push(shop_admin_create_product_path)`
 link changes but body widget stays the same.

If I refresh the page, it is ok. But I have to route user with onTap functions in sidebar buttons.

**Comment by tomgilder** [comment]
Try adding a `key` to `ShopAdminView` and see if that helps. 

If not, please post a small example app showing the issue.

**Comment by batuhand** [comment]
> Try adding a `key` to `ShopAdminView` and see if that helps.
> 
> If not, please post a small example app showing the issue.

Adding a key solved the problem, thanks a lot.
