### ISSUE TITLE
Is there any possibility to have route for pop-up?

### ISSUE THREAD

**Issue by erimeilis** [tomgilder/routemaster#309]
I'm using TabPage for the whole application and need some tabs to open pop-ups. Is it possible to have such routes or maybe simply add routeless points with custom onTap to tab list?
I've found https://github.com/tomgilder/routemaster/wiki/Path-hierarchy this, but seems it's not gonna work

**Comment by dfdgsdfg** [comment]
You can do it with `DialogRoute`. 

Here is an example code.

Maybe this example should on the docs. 😄 

```dart
late final signOutStateRouteMap = RouteMap(
  onUnknownRoute: (_) => const Redirect('/'),
    routes: {
      '/home/my_dialog': (_) {
         return const MyDialogPage();
      },
   }
);

class MyDialogPage extends Page<void> {
  const MyDialogPage({super.key});

  @override
  String get name => 'my_dialog';

  @override
  Route<void> createRoute(BuildContext context) {
    return DialogRoute(
      context: context,
      barrierDismissible: false,
      builder: (context) => const MyDialog(),
      settings: this,
    );
  }
}
```

**Comment by erimeilis** [comment]
It works, thank you!
