### ISSUE TITLE
Return values

### ISSUE THREAD

**Issue by tomgilder** [tomgilder/routemaster#56]
With the classic Navigator, you can return values from pushes:

`final result = await Navigator.of(context).pushNamed('route');`
`Navigator.of(context).pop('result');`

Currently, Routemaster has no support for this.

**Questions**
1. Is this something worth adding? How popular is this?
2. Can this actually be done with Navigator 2.0 and global routing?

If this isn't added, there should be documentation on how to pass values to previous pages.

**Comment by camillobucciarelli** [comment]
This missing feature blocked us to use Routemaster in our projects. We use this feature many times to decide if refresh previous page data.

**Comment by tomgilder** [comment]
Good to know, thanks for the info. I suspect this will be a popular feature request, the problem is Navigator 2.0 doesn't really support it 😕 

I was researching yesterday how Routemaster can support it, but it's a bit tricky. Any ideas are welcome, and if anyone has examples of this being done in Navigator 2.0 I'd love to see them.

**Comment by tomgilder** [comment]
Actually, this might not be as hard as I thought! Watch this space 😁

**Comment by tomgilder** [comment]
Okay, yep, it's possible - but I'm planning to do this via a slightly different API.

Calling `push<T>()` will return a `NavigationResult<T>` object, with a `Future<T> value` property for getting the result.

`final result = await Routemaster.of(context).push<String>('profile/1').result;`

The reasons for `push` not returning a future are:

1. When using `pedantic`, it wants all futures to be awaited. This is highly annoying for pushes that won't return values.
2. This will allow Routemaster to potentially return more things in the future about the pushed route. I'm not sure what though 😁 

Would appreciate thoughts on the naming of `NavigationResult` and `.result` property.

Also, this won't be available on `.replace()` currently.

**Comment by tomgilder** [comment]
I think this is ready, but I'm concerned the API is a bit confusing and would love some feedback 

You can currently get the result via the `.result` property:

`final result = await Routemaster.of(context).push<String>('profile/1').result;`

You can also get the top-most `Route` that was created from this navigation:

`final route = await Routemaster.of(context).push<String>('profile/1').route;`

...not entirely sure if this is useful though - the only useful thing I can think of is being able to access the animation of the incoming route. Is it worth adding this?

**Comment by tomgilder** [comment]
@camillobucciarelli hope this unblocks you, please let me know if the API makes sense 😁

**Comment by EdsonBueno** [comment]
Hi @tomgilder .
Thank you for this feature! I need it badly haha
When are you uploading 0.7.0 to pub.dev?

**Comment by tomgilder** [comment]
@EdsonBueno published! Please note the breaking changes, especially the `path` one - https://github.com/tomgilder/routemaster#migration-from-060-to-070

**Comment by camillobucciarelli** [comment]
@tomgilder These days I migrate my projects to route master and all works fine, thanks a lot.  😁

**Comment by tomgilder** [comment]
@camillobucciarelli you're welcome! Glad you like it

**Comment by darkstarx** [comment]
Hi guys!
@tomgilder is there any option to pop the result using the `history` api like `Routemaster.of(context).history.back(anyResultHere)`?
