### ISSUE TITLE
Guard builder BuildContext

### ISSUE THREAD

**Issue by RedTech64** [tomgilder/routemaster#64]
I noticed you're replacing the child property with a builder for Guard. Is there a way to allow for BuildContext to be included with the builder? I don't know anything about Navigator 2.0 so I'm sure if this is possible, but since context is included in the other two properties of Guard I figured maybe could be.

**Comment by tomgilder** [comment]
Good point, it does feel a bit weird that it's passed into `validate` but not `builder`.

There's a balance here; I'm keen to make the methods in the route map have as few parameters as possible, to aid readability and reduce confusion.

The only `context` that can be provided is the context from the Router, so it won't be different per route build - and you could already get it currently too.

```dart
RoutemasterDelegate(
  routesBuilder: (BuildContext context) { // This context here...
    return RouteMap(
      routes: {
        '/': (info) => Redirect('/two'),
        '/two': (info) => Guard(
              validate: (info, context) => true, // ...is the same as this one here...
              builder: () => MaterialPage<void>(child: MyPage()), // ...should it be passed here too?
            ),
      },
    );
  },
)
```

I'm thinking it should either be provided to both, or neither.

Is there a particular use case you were thinking of here?

**Comment by RedTech64** [comment]
I'm using Bloc in my project and was trying to find a way to access some blocs to provide to the page. I didn't realize you could wrap the RouteMap with the delegate to get the context, so I think I can just use that for my use case. As for the API design, it seems like builders always have at least a BuildContext parameter so I feel like it should have it. But on the other hand, it does seem messy to have it passed on every field of Guard.

**Comment by tomgilder** [comment]
Having thought about this, I'm going to no longer recommend `Guard` as the best way to protect routes, see [this comment](https://github.com/tomgilder/routemaster/issues/19#issuecomment-831226973).

I might have to change the routing map to provide a context to every route, but only if that context will ever change (such as injecting new dependencies) - otherwise there's no point in passing it as you can easily get it from `routesBuilder`.

**Comment by tomgilder** [comment]
I'm closing this for now as you can get a `context` as shown above.
