### ISSUE TITLE
popping routes will not remember the query parameters

### ISSUE THREAD

**Issue by ened** [tomgilder/routemaster#67]
Given the example project here: https://github.com/ened/routemaster_eval

Please run it on a mac or tablet to see the following behavior:

- Scroll the list a bit and select a item
- The detail screen will show (due to a route change to `/?id=123`)
- Tap on "final  link" to see the final page, route changed to `/detail/final?id=123`
- Tap back will return to `/`. Th expectation is to route back to `/?id=123` on back press.

**Comment by tomgilder** [comment]
Good spot, thank you for the report and example.

**Comment by ened** [comment]
That was quick! Thank you @tomgilder.

**Comment by ened** [comment]
@tomgilder btw, please push the new version to pub :) Seems like it's already tagged in GitHub?

**Comment by tomgilder** [comment]
@ened done! :-)

Please note the breaking changes, especially the `path` one - https://github.com/tomgilder/routemaster#migration-from-060-to-070
