### ISSUE TITLE
Swapping routing map does not switch displayed page

### ISSUE THREAD

**Issue by ntoljic** [tomgilder/routemaster#93]
Firstly, I am not sure if it is a bug or just a wrong assumption of mine.
Swapping routing maps at runtime based on the loggedIn state of my app seems to only work sometimes.

My routing maps look as follows:

```
final loginRoutes = RouteMap(
  routes: {
    '/login': (routeData) {
      print('about to return loginPage');
      return MaterialPage(child: LoginPage());
    },
  },
  onUnknownRoute: (route, context) {
    print('redirecting to loginPage');
    return Redirect('/login');
  },
);

final routes = RouteMap(
  routes: {
    '/': (_) => MaterialPage(child: HomePage()),
    '/test': (_) => MaterialPage(child: TestPage()),
  },
  onUnknownRoute: (route, context) => MaterialPage(child: NotFoundPage()),
);
```

On app start the correct routing map is picked and displayed based on the loggedIn state.
Logging in also works, i.e. the LoginPage is displayed, the loggedIn state set and the HomePage shown.
Logging out is where it gets tricky:
While on the HomePage, changing the loggedIn state causes the LoginPage to be displayed.
While on the TestPage however, changing the loggedIn state does *not* cause the LoginPage to be displayed. Instead the TestPage remains shown.
I have tried switching my pages around to see if the page content somehow causes it, but in the end I was able to reproduce the behaviour even with my TestPage which has basically no content at all.
This happens on any page that is not the 'home' page (i.e. '/').

Subsequent navigation does indeed lead to the LoginPage, but I'd expect the current page to be replaced immediately.
It might be relevant that the above print statements in `loginRoutes` do get executed.

**Comment by ntoljic** [comment]
I have just realized what the culprit was.
Since I copied the sample code from the readme my `MaterialPage` instances did not have their `key` set.
Updating my routes to the following solved the issue for me:

```
final loginRoutes = RouteMap(
  routes: {
    '/login': (routeData) {
      print('about to return loginPage');
      return MaterialPage(ValueKey('LoginPage'), child: LoginPage());
    },
  },
  onUnknownRoute: (route, context) {
    print('redirecting to loginPage');
    return Redirect('/login');
  },
);

final routes = RouteMap(
  routes: {
    '/': (_) => MaterialPage(ValueKey('HomePage'), child: HomePage()),
    '/test': (_) => MaterialPage(ValueKey('TestPage'), child: TestPage()),
  },
  onUnknownRoute: (route, context) => MaterialPage(ValueKey('NotFoundPage'), child: NotFoundPage()),
);
```

Maybe the readme could be extended to mention this fact or the examples adapted?

**Comment by tomgilder** [comment]
Good point, will add to the documentation 👍 

Glad you got it solved, thanks!

**Comment by ntoljic** [comment]
In case anyone stumbles across this issue, the problem was not the missing key.
The problem was that I was calling `Routemaster.of(context).push('/test');` with an open navigation drawer.
Looking at the book store example I saw that in this case I have to call `Navigator.pop(context)`.
I am not completely sure why this is required but at least I got it working. My guess is that opening/closing the navigation drawer changes the navigation stack 🤔 

@tomgilder Please disregard my suggestion of adding the `key` to the docs, it is not actually necessary and just masked the real issue I was having.
