### ISSUE TITLE
Routemaster conflicts with url_strategy

### ISSUE THREAD

**Issue by AbhishekDoshi-Bacancy** [tomgilder/routemaster#95]
I have created a splash screen kinda thing and in it's initState I am adding a timer and moving to next screen after 1 second it should move to next screen, however, it doesn't move to the next screen when using replace()

**Comment by tomgilder** [comment]
Hi, what platform is this on please? There are issues with `replace()` on the web currently - users can sometimes go back to the page - but the navigation should work

**Comment by tomgilder** [comment]
And any code sample would be useful

**Comment by AbhishekDoshi-Bacancy** [comment]
@tomgilder Sure would provide a code sample

**Comment by AbhishekDoshi-Bacancy** [comment]
**main.dart**
```
import 'package:flutter/material.dart';
import 'package:knuggies/screens/home.dart';
import 'package:knuggies/screens/login.dart';
import 'package:knuggies/screens/splash.dart';
import 'package:knuggies/utils/string_constants.dart';
import 'package:routemaster/routemaster.dart';
import 'package:url_strategy/url_strategy.dart';

void main() {
  setPathUrlStrategy();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final _routerDelegate = RouteMap(
    routes: {
      '/': (_) => MaterialPage(child: SplashScreen()),
      '/home': (_) => MaterialPage(child: HomeScreen()),
      '/login': (_) => MaterialPage(child: LoginScreen()),
    },
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.dark,
      theme: ThemeData.dark(),
      title: StringConstants.appName,
      routerDelegate: RoutemasterDelegate(routesBuilder: (context) => _routerDelegate),
        routeInformationParser: RoutemasterParser(),
    );
  }
}
```



**splash.dart**
```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:knuggies/utils/string_constants.dart';
import 'package:routemaster/routemaster.dart';

class SplashScreen extends StatefulWidget {
  @override
  _SplashScreenState createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  void initState() {
    Timer(
      Duration(seconds: 2),
      () => Routemaster.of(context).replace('home'),
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Image.network(
          StringConstants.splashLogoURL,
          height: MediaQuery.of(context).size.width / 10.0,
        ),
      ),
    );
  }
}
```

**Comment by AbhishekDoshi-Bacancy** [comment]
@tomgilder if i use push instead of replace, it works perfectly

**Comment by tomgilder** [comment]
You need to  replace remove the dependency on `url_strategy` and change `setPathUrlStrategy();` to `Routemaster.setPathUrlStrategy();`

I'll try to make Routemaster compatible with `url_strategy` or at least add something to the documentation.

**Comment by AbhishekDoshi-Bacancy** [comment]
oh okk gotcha. would try that @tomgilder thanks for the instant help. Was using this in production level app.

**Comment by AbhishekDoshi-Bacancy** [comment]
Hey thanks! This works perfectly. I had one more question, it might be off from the issue topic.
How can I pass data from one screen to another screen if I am using `push()` without showing it into URL.
Eg: I have made an API call in 1st page and now I wish to move that entire object to 2nd page. 
It will be great if you can provide some reference example or docs for this scenario.
@tomgilder

**Comment by tomgilder** [comment]
@AbhishekDoshi-Bacancy glad it's fixed!

Instead of passing data between pages, that data should be in some global state management. If the user navigates to the second URL directly your app will have to fetch the data from API. 

This has also been brought up in another issue: https://github.com/tomgilder/routemaster/issues/96

Closing this for now, but feel free to make any suggestions about passing data.
