### ISSUE TITLE
Directly going to a particular route doesn't work in release. 

### ISSUE THREAD

**Issue by AbhishekDoshi26** [tomgilder/routemaster#98]
Hey! So I have successfully implemented route master and it works perfectly for Navigation from one page to another with URL change. You can check out at: https://knuggies.netlify.app
First Splash screen is there and then home screen.
However, if you directly go to https://knuggies.netlify.app/home it shows 404.

However, the same steps works with localhost while debugging.

Do I need to setup anything for the same?
The sample code can be checked in issue #95

**Comment by tomgilder** [comment]
Your server is serving that 404 page rather than the Flutter app - it's a server config issue, nothing to do with Routemaster or Flutter I'm afraid.

It'll almost certainly work if you use the default hash path strategy.
